-- Generated by LuaWatch Designer
-- Requires SimpleUI C++ implementation

currentPage = "main"

-- Persistent scroll variables
if list_6_scroll == nil then list_6_scroll = 0 end

function draw_main()
    -- urlbar
    if ui.button(20, 410, 370, 30, "New Element", 12678) then
        print("Button urlbar clicked")
    end
    -- btn_back
    if ui.button(60, 445, 90, 40, "back", 10665) then
        print("Button btn_back clicked")
    end
    -- btn_reload
    if ui.button(155, 445, 80, 40, "reload", 10665) then
        print("Button btn_reload clicked")
    end
    -- btn_menu
    if ui.button(240, 445, 115, 40, "menu", 22289) then
        currentPage = "quickmenu"
    end
    -- statustext
    ui.text(95, 485, "Done (150ms)", 1, 65535)
    -- List: list_6
    list_6_scroll = ui.BeginList(0, 35, 410, 370, list_6_scroll, 400)
    ui.EndList()

    -- batttext
    ui.text(240, 0, "100%", 2, 65535)
    -- timetext
    ui.text(90, 0, "9:42", 2, 65535)
end

function draw_quickmenu()
    -- bookmarkadd
    if ui.button(20, 100, 180, 60, "add to bm", 10665) then
        print("Button bookmarkadd clicked")
    end
    -- bookmarks
    if ui.button(210, 100, 180, 60, "bookmarks", 10665) then
        print("Button bookmarks clicked")
    end
    -- historybtn
    if ui.button(20, 170, 180, 60, "history", 10665) then
        print("Button historybtn clicked")
    end
    -- clrhistory
    if ui.button(210, 170, 180, 60, "clrhistory", 10665) then
        print("Button clrhistory clicked")
    end
    -- exitbtn
    if ui.button(30, 405, 140, 45, "exit", 59783) then
        print("Button exitbtn clicked")
        hw.reboot()
    end
    -- text_6
    ui.text(25, 245, "free psram:", 1, 65535)
    -- aboutinfotext
    ui.text(125, 470, "webprimitive 0.1", 1, 65535)
    -- urlinfobox
    ui.text(25, 275, "https://google.com", 1, 65535)
    -- backbtn
    if ui.button(255, 405, 120, 45, "back", 10665) then
        currentPage = "main"
    end
end

function draw_urlenter()
    -- url_enter_text
    ui.text(10, 90, " ", 2, 65535)
    -- cancelbtn
    if ui.button(90, 10, 105, 60, "cancel", 10665) then
        currentPage = "main"
    end
    -- gobtn
    if ui.button(205, 10, 110, 60, "go", 10665) then
        print("Button gobtn clicked")
    end
    -- t9kbd_1
    if ui.button(15, 175, 120, 55, "New Element", 10665) then
        print("Button t9kbd_1 clicked")
    end
    -- t9kbd_2
    if ui.button(145, 175, 120, 55, "New Element", 10665) then
        print("Button t9kbd_2 clicked")
    end
    -- t9kbd_3
    if ui.button(275, 175, 125, 55, "New Element", 10665) then
        print("Button t9kbd_3 clicked")
    end
    -- t9kbd_7
    if ui.button(15, 305, 120, 55, "New Element", 10665) then
        print("Button t9kbd_7 clicked")
    end
    -- t9kbd_9
    if ui.button(275, 305, 125, 55, "New Element", 10665) then
        print("Button t9kbd_9 clicked")
    end
    -- t9kbd_8
    if ui.button(145, 305, 120, 55, "New Element", 10665) then
        print("Button t9kbd_8 clicked")
    end
    -- t9kbd_5
    if ui.button(145, 240, 120, 55, "New Element", 10665) then
        print("Button t9kbd_5 clicked")
    end
    -- t9kbd_4
    if ui.button(15, 240, 120, 55, "New Element", 10665) then
        print("Button t9kbd_4 clicked")
    end
    -- t9kbd_6
    if ui.button(275, 240, 125, 55, "New Element", 10665) then
        print("Button t9kbd_6 clicked")
    end
    -- t9kbd_12
    if ui.button(275, 370, 125, 55, "New Element", 10665) then
        print("Button t9kbd_12 clicked")
    end
    -- t9kbd_11
    if ui.button(145, 370, 120, 55, "New Element", 10665) then
        print("Button t9kbd_11 clicked")
    end
    -- t9kbd_10
    if ui.button(15, 370, 120, 55, "New Element", 10665) then
        print("Button t9kbd_10 clicked")
    end
end

function draw()
    ui.rect(0, 0, 410, 502, 0) -- Clear background

    if currentPage == "main" then
        draw_main()
    elseif currentPage == "quickmenu" then
        draw_quickmenu()
    elseif currentPage == "urlenter" then
        draw_urlenter()
    end
end
